### ISSUE TITLE
Clockwise Direction for M

### ISSUE THREAD

**Issue by wubr** [chrishunt/rubiks-cube#7]
Readme says 'When you see M, then rotate this slice 90 degrees clockwise. To figure out which direction is clockwise, look at the L face.'  Shouldn't this be based on the R face, per your Golden Gate Ruby talk?

**Comment by chrishunt** [comment]
Ah, dang, I must have said it wrong at GoGaRuCo :frowning: I'm sorry about that. Thanks for finding the mistake.

The correct direction is indeed as if you were looking at the **L** face. Checkout the [speedcubing wiki](http://www.speedsolving.com/wiki/index.php/3x3x3_notation#Slice_Turns) for more.
